name: Build Kernel
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Configure Rustup
        run: |
          echo ::group::Rustup Nightly
          rustup override set nightly
          echo ::endgroup::
          echo ::group::Rustup add rust-src
          rustup component add rust-src
          echo ::endgroup::
      - name: Install Xargo
        run: cargo install xargo
      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: Build Kernel
        run: |
          bash ./build

      - name: Upload Kernel
        uses: actions/upload-artifact@v2
        with:
          name: kernel
          path: ./target/kernel.img

      - name: Upload Full Image ZIP (with firmware)
        uses: actions/upload-artifact@v2
        with:
          name: image-with-firmware
          path: |
            ./target/kernel.img
            ./firmware/start.elf
            ./firmware/fixup.dat
            ./firmware/bootcode.bin
            ./firmware/LICENCE.broadcom
            

      