name: Build Kernel
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
      - name: Configure Rustup
        run: |
          echo ::group::Rustup Nightly
          rustup override set nightly
          echo ::endgroup::
          echo ::group::Rustup add rust-src
          rustup component add rust-src
          echo ::endgroup::

      - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: Build Kernel
        run: |
          bash ./build.sh

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: ./target/kernel.img

      - name: Upload Full Image ZIP (with firmware)
        uses: actions/upload-artifact@v4
        with:
          name: kernel-with-firmware
          path: |
            ./target/kernel.img
            ./firmware/start.elf
            ./firmware/fixup.dat
            ./firmware/bootcode.bin
            ./firmware/LICENCE.broadcom

  release:
    name: Publish Release
    needs: build
    if: success() && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: kernel
          path: kernel
      - uses: actions/download-artifact@v5
        with:
          name: kernel-with-firmware
          path: kernel-with-firmware

      - name: Zip Kernel with Firmware
        run: zip -r kernel-with-firmware.zip kernel-with-firmware

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
          artifacts: "./kernel/kernel.img,kernel-with-firmware.zip"
